"""Self-contained HTML P&L report — inline SVG, no external assets."""
from __future__ import annotations

from pathlib import Path


def _equity_svg(equities: list[float], width: int = 720, height: int = 220) -> str:
    if len(equities) < 2:
        return "<p class='dim'>Not enough history for a chart yet — run a few cycles.</p>"
    lo, hi = min(equities), max(equities)
    span = (hi - lo) or 1.0
    pad = 8
    points = " ".join(
        f"{pad + i * (width - 2 * pad) / (len(equities) - 1):.1f},"
        f"{height - pad - (e - lo) / span * (height - 2 * pad):.1f}"
        for i, e in enumerate(equities)
    )
    up = equities[-1] >= equities[0]
    color = "#3fb950" if up else "#f85149"
    return (
        f'<svg viewBox="0 0 {width} {height}" role="img" aria-label="equity curve">'
        f'<polyline fill="none" stroke="{color}" stroke-width="2" points="{points}"/>'
        "</svg>"
    )


def render_report(history: list[dict], out_path: str | Path) -> None:
    if history:
        first, last = history[0], history[-1]
        equities = [h["equity"] for h in history]
        total = last["equity"] / first["equity"] - 1.0
        stats = f"""
  <div class="tiles">
    <div class="tile"><div class="label">equity</div><div class="value">${last['equity']:,.0f}</div></div>
    <div class="tile"><div class="label">total return</div>
      <div class="value {'up' if total >= 0 else 'down'}">{total * 100:+.2f}%</div></div>
    <div class="tile"><div class="label">position</div>
      <div class="value">{last['target_qty']:g} {last['symbol']}</div></div>
    <div class="tile"><div class="label">cycles</div><div class="value">{len(history)}</div></div>
  </div>
  {_equity_svg(equities)}
  <p class="dim">first cycle {first['ts'][:10]} · last cycle {last['ts'][:10]} ·
     last signal weight {last['weight']:g} · last price ${last['price']:,.2f}</p>"""
    else:
        stats = "<p class='dim'>No cycles recorded yet. Run <code>quantsim live run</code> first.</p>"

    html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>quantsim live — P&amp;L</title>
<style>
  body {{ background:#0d1117; color:#e6edf3; font-family:-apple-system,BlinkMacSystemFont,
         "Segoe UI",Roboto,sans-serif; max-width:780px; margin:40px auto; padding:0 16px; }}
  h1 {{ font-size:1.4rem; }} .dim {{ color:#8b949e; font-size:.85rem; }}
  .tiles {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr));
            gap:12px; margin:20px 0; }}
  .tile {{ background:#161b22; border:1px solid #30363d; border-radius:10px; padding:14px; }}
  .label {{ color:#8b949e; font-size:.75rem; text-transform:uppercase; letter-spacing:.06em; }}
  .value {{ font-size:1.3rem; font-weight:600; margin-top:4px; }}
  .up {{ color:#3fb950; }} .down {{ color:#f85149; }}
  svg {{ width:100%; background:#161b22; border:1px solid #30363d; border-radius:10px; }}
  code {{ background:#161b22; padding:2px 6px; border-radius:6px; }}
</style></head><body>
<h1>📈 quantsim live — paper P&amp;L</h1>
{stats}
<p class="dim">Generated by <a style="color:#58a6ff"
  href="https://github.com/hilothefunnydog123-coder/quantsim">quantsim live</a>.
  Paper money only — this is a research toy, not investment advice.</p>
</body></html>"""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html)
